// Highlight Engine
// Maps the current URL (and a small amount of DOM context) to a list of
// selectors that should blink. Used by aws-guide-playwright.mjs.
//
// Each profile has:
//   id:        stable identifier referenced from WorkshopPlan.expectedProfile
//   match:     (url) => boolean
//   label:     short human-readable label for logs
//   selectors: array of selector strings. Supports:
//     - normal CSS selectors
//     - "text=foo"  (case-insensitive substring match against innerText/value)
//     - "aria=foo"  (matches aria-label / aria-labelledby substring)
//   gateOnChoice (optional): selectors are only applied when injectionState.signinChoice
//     equals one of the listed values. Used so the AWS sign-in landing page does
//     NOT blink upfront — the user must pick "existing" or "new" first.
//
// Derived selectors are merged from user/derived-profiles.json when that file
// exists (generated by scripts/extract-profiles.mjs from behavior_log.jsonl).
// They are prepended so real observed selectors are tried before the hardcoded
// fallbacks.

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

export const PROFILES = [
  {
    id: 'aws-home',
    label: 'AWS Home — Sign in to the Console',
    match: (u) =>
      u.includes('aws.amazon.com') &&
      !u.includes('console.aws.amazon.com') &&
      !u.includes('signin.aws.amazon.com') &&
      !u.includes('signup.aws.amazon.com') &&
      !u.includes('portal.aws.amazon.com'),
    selectors: [
      // 2026 Rigel design system: hero CTA is `<a role="button">` with a
      // semantic data-rigel-analytics attribute. Hashed `rghr_*` classes
      // are unstable — anchor on the analytics attribute + bare host href.
      'a[data-rigel-analytics*="\\"variant\\":\\"primary\\""][href="https://console.aws.amazon.com/"]',
      'a[role="button"][href="https://console.aws.amazon.com/"]',
      'a[href="https://console.aws.amazon.com/"][data-rigel-analytics*="Button"]',
      // Legacy lb-btn skin (older home page variants — kept as fallback)
      'a.lb-btn-orange[href*="console.aws.amazon.com"]',
      'a.lb-btn[href*="console.aws.amazon.com/console/home"]',
      'a[data-testid="signin-button"]',
      'header a[href*="console.aws.amazon.com/console/home"]',
      'a[href="https://console.aws.amazon.com/console/home"]',
      'a[href^="https://console.aws.amazon.com/console/home"]',
      'text=Sign in to the Console',
      'text=Sign In to the Console',
    ],
  },
  {
    // The AWS sign-in landing page. Do NOT blink anything on the form itself.
    // The Playwright overlay shows a Sign-in / Create-account picker and only
    // after the user picks does signin-root-existing or signup-root-new become
    // the active profile.
    id: 'signin-choice',
    label: 'Sign-in — Choose existing account or create new',
    match: (u) =>
      u.includes('signin.aws.amazon.com/signin') ||
      u.includes('signin.aws.amazon.com/?') ||
      u.includes('signin.aws.amazon.com/oauth'),
    selectors: [],
  },
  // Sign-in corridor profiles: no blinking by design. Real users have many
  // valid paths through sign-in (root, IAM, federated, password manager
  // autofill, hardware MFA, email OTP, …). Highlighting one path would
  // confuse users on a different path. The signinChoice the user picked
  // upstream is still tracked and forwarded to the presenter for analytics
  // (how many pick root vs. IAM vs. new account).
  {
    id: 'signin-root-existing',
    label: 'Sign-in — Root email account (analytics only)',
    match: (u) => u.includes('signin.aws.amazon.com'),
    gateOnChoice: ['root'],
    selectors: [],
  },
  {
    id: 'signin-root-iam',
    label: 'Sign-in — IAM user credentials (analytics only)',
    match: (u) => u.includes('signin.aws.amazon.com'),
    gateOnChoice: ['iam'],
    selectors: [],
  },
  {
    id: 'signup-root-new',
    label: 'Sign-up — Create a new AWS account (analytics only)',
    match: (u) =>
      u.includes('signin.aws.amazon.com/signin') ||
      u.includes('signin.aws.amazon.com/?') ||
      u.includes('signup.aws.amazon.com') ||
      u.includes('portal.aws.amazon.com/billing/signup'),
    gateOnChoice: ['new'],
    selectors: [],
  },
  {
    id: 'signin-password',
    label: 'Sign-in — Password (no highlight)',
    match: (u) => u.includes('signin.aws.amazon.com/authenticate') || u.includes('signin.aws.amazon.com/password'),
    selectors: [],
  },
  {
    id: 'signin-mfa',
    label: 'Sign-in — Email / MFA Code (no highlight)',
    match: (u) => u.includes('signin.aws.amazon.com/mfa') || u.includes('signin.aws.amazon.com/email-otp') || u.includes('signin.aws.amazon.com/challenge'),
    selectors: [],
  },
  {
    id: 'console-home',
    label: 'Console Home — Search EC2',
    match: (u) => u.includes('console.aws.amazon.com/console/home') || /console\.aws\.amazon\.com\/?($|\?)/.test(u),
    selectors: [
      'input#awsc-concierge-input',
      'input[data-testid="awsc-concierge-input"]',
      'input[placeholder="Search"]',
      'input[aria-label="Search"]',
      'input[type="search"]',
      'a[data-testid="services-search-result-link-ec2"]',
      'aria=Search',
    ],
  },
  {
    id: 'ec2-launch-form',
    label: 'EC2 — Launch Instance Form',
    match: (u) => u.includes('console.aws.amazon.com/ec2/') && u.includes('#LaunchInstances'),
    selectors: [
      'input[placeholder="e.g. My Web Server"]',
      'input[placeholder*="My Web Server"]',
      '[data-testid="name-container"] input',
      '[data-testid="getting-started-tile-0"]',
      '[data-testid^="getting-started-tile-"]',
      'text=Free tier eligible',
      'text=Launch instance',
    ],
  },
  {
    id: 'ec2-dashboard',
    label: 'EC2 Dashboard — Launch instance',
    match: (u) =>
      u.includes('console.aws.amazon.com/ec2/') &&
      !u.includes('#LaunchInstances'),
    selectors: [
      'button[data-testid="launch-instance"]',
      'button[data-analytics-funnel-substep="launch-instance"]',
      'awsui-button[variant="primary"] button',
      '[data-testid="launch-instance-button"]',
      'a[href*="LaunchInstances"]',
      'button:has-text("Launch instance")',
      'text=Launch instance',
      'text=Launch instances',
    ],
  },
];

// Merge selectors derived from behavior_log.jsonl (via scripts/extract-profiles.mjs).
// The file only exists after the extraction script has run — missing file is not an error.
// signin-choice intentionally keeps selectors:[] because first-match semantics mean
// any log entry on the signin URL matches signin-choice (listed first in PROFILES),
// so no derived selectors accumulate for it.
try {
  const derivedPath = fileURLToPath(new URL('./derived-profiles.json', import.meta.url));
  const derivedMap = JSON.parse(readFileSync(derivedPath, 'utf8'));
  for (const profile of PROFILES) {
    const derived = derivedMap[profile.id] ?? [];
    const highConf = derived.filter((d) => d.count >= 2).map((d) => d.selector);
    if (highConf.length > 0) {
      profile.selectors = [...new Set([...highConf, ...profile.selectors])];
    }
  }
} catch { /* derived-profiles.json absent — use hardcoded selectors only */ }

function findProfileForUrl(url) {
  if (typeof url !== 'string') return null;
  return PROFILES.find((p) => {
    try { return p.match(url); } catch { return false; }
  }) ?? null;
}

export function getProfileById(profileId) {
  return PROFILES.find((p) => p.id === profileId) ?? null;
}

export function getHighlightsForUrl(url, { signinChoice = null } = {}) {
  const profile = findProfileForUrl(url);
  if (!profile) return { id: 'none', label: 'No match', selectors: [] };

  // signin-choice landing: render no highlights until the user picks one of three paths.
  if (profile.id === 'signin-choice') {
    if (signinChoice) {
      const targetId =
        signinChoice === 'root' ? 'signin-root-existing' :
        signinChoice === 'iam'  ? 'signin-root-iam' :
        signinChoice === 'new'  ? 'signup-root-new' : null;
      if (targetId) {
        const target = getProfileById(targetId);
        if (target) return { id: target.id, label: target.label, selectors: target.selectors.slice() };
      }
    }
    return { id: profile.id, label: profile.label, selectors: [] };
  }

  // Profiles gated on a choice — only emit selectors when the gate matches.
  if (Array.isArray(profile.gateOnChoice) && !profile.gateOnChoice.includes(signinChoice)) {
    return { id: profile.id, label: profile.label, selectors: [] };
  }

  return { id: profile.id, label: profile.label, selectors: profile.selectors.slice() };
}

// Ordered sequence of all profiles in the expected navigation flow.
// Profiles marked transitional:true sit in the sign-in corridor between
// aws-home and console-home — the exact path varies per user (OAuth redirect,
// password, MFA, etc.) so they are treated as "in transit" rather than wrong.
export const NAVIGATION_SEQUENCE = [
  { id: 'aws-home',             transitional: false },
  { id: 'signin-choice',        transitional: true  },
  { id: 'signin-root-existing', transitional: true  },
  { id: 'signin-root-iam',      transitional: true  },
  { id: 'signup-root-new',      transitional: true  },
  { id: 'signin-password',      transitional: true  },
  { id: 'signin-mfa',           transitional: true  },
  { id: 'console-home',         transitional: false },
  { id: 'ec2-dashboard',        transitional: false },
  { id: 'ec2-launch-form',      transitional: false },
];

const TRANSITIONAL_IDS = new Set(
  NAVIGATION_SEQUENCE.filter((n) => n.transitional).map((n) => n.id)
);

// Compare the participant's current page URL with the step's expected profile.
// Returns 'correct' | 'wrong' | 'unknown'.
//   - 'correct'  → the URL matches the profile the step expects
//   - 'wrong'    → the URL is clearly at a different non-transitional step
//   - 'unknown'  → URL is unrecognized, or URL is in the sign-in corridor
//                  (transitional) while the step expects a post-signin profile
export function expectedUrlMatcher(expectedProfile, url) {
  if (!expectedProfile) return 'unknown';
  const profile = findProfileForUrl(url);
  if (!profile) return 'unknown';
  if (profile.id === expectedProfile) return 'correct';
  if (TRANSITIONAL_IDS.has(profile.id) && !TRANSITIONAL_IDS.has(expectedProfile)) return 'unknown';
  return 'wrong';
}

// Code that runs INSIDE the page (passed to frame.evaluate as a string).
// Kept self-contained — no closures, no imports.
export const FRAME_INJECTION_FN = function applyHighlights(selectors) {
  if (!document.body) return 0;

  if (!document.getElementById('w-style')) {
    const s = document.createElement('style');
    s.id = 'w-style';
    s.dataset.wRed = '1';
    s.textContent = `
      @keyframes w-ripple {
        0%   { outline: 4px solid rgba(239,68,68,1);    outline-offset: 0px;  box-shadow: 0 0 0 0    rgba(239,68,68,0.95), 0 0 18px 4px  rgba(239,68,68,0.85); background-color: rgba(239,68,68,0.18); }
        45%  { outline: 6px solid rgba(220,38,38,1);    outline-offset: 6px;  box-shadow: 0 0 0 18px rgba(239,68,68,0.45), 0 0 36px 10px rgba(239,68,68,0.7);  background-color: rgba(239,68,68,0.28); }
        100% { outline: 8px solid rgba(185,28,28,0.95); outline-offset: 14px; box-shadow: 0 0 0 36px rgba(239,68,68,0),    0 0 60px 18px rgba(239,68,68,0);    background-color: rgba(239,68,68,0.10); }
      }
      [data-w-hl] {
        animation: w-ripple 0.6s infinite ease-out !important;
        border-radius: 8px !important;
        position: relative !important;
        z-index: 2147483646 !important;
      }
    `;
    (document.head || document.documentElement).appendChild(s);
  }

  const isVisible = (el) => {
    if (!el || !el.getBoundingClientRect) return false;
    const r = el.getBoundingClientRect();
    if (r.width < 4 || r.height < 4) return false;
    const cs = window.getComputedStyle(el);
    if (cs.display === 'none' || cs.visibility === 'hidden' || cs.opacity === '0') return false;
    return true;
  };

  const matchSelector = (sel) => {
    if (typeof sel !== 'string' || !sel) return [];
    if (sel.startsWith('text=')) {
      const needle = sel.slice(5).trim().toLowerCase();
      if (!needle) return [];
      const out = [];
      const candidates = document.querySelectorAll(
        'button, a, span, label, div[role="button"], input[type="submit"], input[type="button"], [role="link"], h1, h2, h3'
      );
      candidates.forEach((el) => {
        const t = (el.innerText || el.value || el.textContent || '').trim().toLowerCase();
        if (t && t.includes(needle) && t.length < 200) out.push(el);
      });
      return out;
    }
    if (sel.startsWith('aria=')) {
      const needle = sel.slice(5).trim().toLowerCase();
      if (!needle) return [];
      return Array.from(document.querySelectorAll('[aria-label]')).filter((el) => {
        const v = (el.getAttribute('aria-label') || '').toLowerCase();
        return v.includes(needle);
      });
    }
    try { return Array.from(document.querySelectorAll(sel)); } catch { return []; }
  };

  const apply = () => {
    document.querySelectorAll('[data-w-hl]').forEach((el) => el.removeAttribute('data-w-hl'));
    if (!Array.isArray(selectors) || selectors.length === 0) return 0;
    let hit = 0;
    for (const sel of selectors) {
      const matches = matchSelector(sel).filter(isVisible);
      if (matches.length > 0) {
        // First-match-wins per selector — avoids highlighting the entire page.
        matches.slice(0, 3).forEach((el) => {
          el.setAttribute('data-w-hl', 'true');
          hit++;
        });
        // Stop after the first selector that produced any hits — gives stable
        // single-target blink instead of every selector firing at once.
        if (hit > 0) break;
      }
    }
    // Vertically center the first highlighted element on initial apply for a
    // given selector-set. Cache the key so MutationObserver re-applications do
    // not fight the user's manual scroll.
    const first = document.querySelector('[data-w-hl]');
    if (first) {
      const scrollKey = JSON.stringify(selectors);
      if (window.__wLastScrollKey !== scrollKey) {
        window.__wLastScrollKey = scrollKey;
        try { first.scrollIntoView({ block: 'center', inline: 'nearest', behavior: 'smooth' }); } catch {}
      }
    }
    return hit;
  };

  window.__wSelectors = selectors;
  if (window.__wObserver) {
    try { window.__wObserver.disconnect(); } catch {}
  }
  window.__wObserver = new MutationObserver(() => {
    // Re-apply only if the highlighted nodes were removed/replaced.
    const live = document.querySelectorAll('[data-w-hl]').length;
    if (live === 0) apply();
  });
  window.__wObserver.observe(document.body, { childList: true, subtree: true });
  return apply();
};

export async function injectBlinkInAllFrames(page, selectors) {
  const fnSource = FRAME_INJECTION_FN.toString();
  const frames = page.frames();
  const results = await Promise.all(
    frames.map(async (frame) => {
      try {
        const hits = await frame.evaluate(`(${fnSource})(${JSON.stringify(selectors)})`);
        return { url: frame.url(), hits: hits || 0 };
      } catch {
        return { url: frame.url(), hits: 0 };
      }
    })
  );
  return results;
}
